// Package infrastructure is implements an adapter to talk to low-level modules.
// # This manifest was generated by ymir. DO NOT EDIT.
package infrastructure

import (
	"os"
	"strings"

	"github.com/kubuskotak/valkyrie"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

// InitializeLogger will set logging format.
func InitializeLogger() {
	zerolog.TimeFieldFormat = zerolog.TimeFormatUnix
	writer := &valkyrie.ZeroWriter{MinLevel: zerolog.DebugLevel}
	log.Logger = zerolog.New(
		zerolog.MultiLevelWriter(os.Stdout, writer)).
		With().Timestamp().Caller().Logger()
	if strings.EqualFold(Envs.App.Environment, Development) {
		log.Logger = log.Output(zerolog.ConsoleWriter{Out: os.Stderr})
	}
}
