App:
  environment: staging
  serviceName: odin

Ports:
  grpc: 5000
  http: 8007
  https: 8003
  metric: 9097

Server:
  timeout: 10s

DB:
  max_open_cons: 5
  max_idle_cons: 1

Telemetry:
  collector_enable: false
  collector_debug: false
  collector_grpc_addr: localhost:4317

Sqlite:
  file: "sqlite://../.data/hello.migration.db?_fk=1"

ProducerHello:
  broker_urls: "localhost:9091"
  topic: "testing-topic"
  client_id: "hello-producer-1"

ConsumerHello:
  broker_urls: "localhost:9091"
  topic: "testing-topic"
  partition: 0
  group_id: "consumer-hello-1"